"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

type Locale = "en" | "hi" | "kn" | "mr" | "ar";

type Dictionary = Record<string, string>;

const dictionaries: Record<Locale, Dictionary> = {
  en: {
    homes: "Homes",
    experiences: "Experiences",
    services: "Services",
    support: "Support",
    hosting: "Hosting",
    travelBnbBrand: "TravelBnb",
    discover: "Discover",
    helpCenter: "Help Center",
    airCover: "AirCover",
    antiDiscrimination: "Anti-discrimination",
    disabilitySupport: "Disability support",
    travelBnbYourHome: "TravelBnb your home",
    airCoverForHosts: "AirCover for Hosts",
    hostingResources: "Hosting resources",
    communityForum: "Community forum",
    newsroom: "Newsroom",
    investors: "Investors",
    careers: "Careers",
    giftCards: "Gift cards",
    topRatedStays: "Top-rated stays",
    privacy: "Privacy",
    terms: "Terms",
    sitemap: "Sitemap",
    host: "Host",
    detectLocation: "Detect my location",
    editHostedPlaces: "Edit hosted places",
    logout: "Log out",
    languageAndRegion: "Language and region",
    currency: "Currency",
    suggestedLanguagesRegions: "Suggested languages and regions",
    chooseLanguageRegion: "Choose a language and region",
    done: "Done",
    where: "Where",
    searchDestinations: "Search destinations",
    checkIn: "Check in",
    checkOut: "Check out",
    addDates: "Add dates",
    who: "Who",
    addGuests: "Add guests",
    adults: "Adults",
    children: "Children",
    infants: "Infants",
    pets: "Pets",
    ages13Plus: "Ages 13 or above",
    ages2to12: "Ages 2–12",
    under2: "Under 2",
    serviceAnimal: "Bringing a service animal?",
    datesLabel: "Dates",
    monthsLabel: "Months",
    flexibleLabel: "Flexible",
    exactDates: "Exact dates",
    homePopularInCity: "Popular homes in Varanasi",
    popularHomesIn: "Popular homes in",
    homeRecentlyHosted: "Recently hosted",
    homeAvailableThisWeekend: "Available this weekend",
    noImage: "No image",
    loading: "Loading…",
    showAllPhotos: "Show all photos",
    aboutThisPlace: "About this place",
    bathrooms: "Bathrooms",
    guestFavourites: "Guest favourites",
    standoutAmenities: "Standout amenities",
    safetyItems: "Safety items",
    locationLabel: "Location",
    loadingMap: "Loading map...",
    coordinates: "Coordinates",
    checkInCaps: "CHECK-IN",
    checkoutCaps: "CHECKOUT",
    guestsCaps: "GUESTS",
    close: "Close",
    reserve: "Reserve",
    wontBeChargedYet: "You won't be charged yet",
    // Host page translations
    letsStartWithBasics: "Let's start with the basics",
    whichBestDescribesYourPlace: "Which of these best describes your place?",
    confirmYourAddress: "Confirm your address",
    countryRegion: "Country/region",
    flatHouseOptional: "Flat, house, etc. (optional)",
    streetAddress: "Street address",
    landmark: "Landmark",
    locality: "Locality",
    city: "City",
    searchOrSelectStateUT: "Search or select State/UT",
    nearbyLandmarkOptional: "Nearby landmark (optional)",
    districtLocalityOptional: "District/locality (optional)",
    cityTown: "City/town",
    stateUT: "State/UT",
    pinCode: "PIN code",
    howManyPeopleCanStay: "How many people can stay here?",
    guests: "Guests",
    bedrooms: "Bedrooms",
    beds: "Beds",
    doesEveryBedroomHaveLock: "Does every bedroom have a lock?",
    yes: "Yes",
    no: "No",
    whatKindOfBathroomsAvailable: "What kind of bathrooms are available to guests?",
    privateAndAttached: "Private and attached",
    connectedToGuestRoom: "Connected to the guest's room and just for them.",
    dedicated: "Dedicated",
    privateButAccessedViaSharedSpace: "Private, but accessed via a shared space like a hallway.",
    shared: "Shared",
    sharedWithOtherPeople: "Shared with other people.",
    whoElseMightBeThere: "Who else might be there?",
    guestsNeedToKnowEncounterOthers: "Guests need to know whether they'll encounter other people during their stay.",
    me: "Me",
    myFamily: "My family",
    otherGuests: "Other guests",
    flatmatesHousemates: "Flatmates/housemates",
    tellGuestsWhatYourPlaceHasToOffer: "Tell guests what your place has to offer",
    canAddMoreAmenitiesAfterPublish: "You can add more amenities after you publish your listing.",
    whatAboutTheseGuestFavourites: "What about these guest favourites?",
    wifi: "Wifi",
    tv: "TV",
    kitchen: "Kitchen",
    washingMachine: "Washing machine",
    freeParkingOnPremises: "Free parking on premises",
    paidParkingOnPremises: "Paid parking on premises",
    airConditioning: "Air conditioning",
    dedicatedWorkspace: "Dedicated workspace",
    doYouHaveAnyStandoutAmenities: "Do you have any standout amenities?",
    pool: "Pool",
    hotTub: "Hot tub",
    patio: "Patio",
    bbqGrill: "BBQ grill",
    outdoorDiningArea: "Outdoor dining area",
    firepit: "Firepit",
    poolTable: "Pool table",
    indoorFireplace: "Indoor fireplace",
    piano: "Piano",
    exerciseEquipment: "Exercise equipment",
    lakeAccess: "Lake access",
    beachAccess: "Beach access",
    skiInOut: "Ski-in/out",
    outdoorShower: "Outdoor shower",
    doYouHaveAnyOfTheseSafetyItems: "Do you have any of these safety items?",
    smokeAlarm: "Smoke alarm",
    firstAidKit: "First aid kit",
    fireExtinguisher: "Fire extinguisher",
    carbonMonoxideAlarm: "Carbon monoxide alarm",
    addSomePhotosOfYourPlace: "Add some photos of your place",
    need5PhotosToGetStarted: "You'll need 5 photos to get started. You can add more or make changes later.",
    addPhotos: "Add photos",
    remove: "Remove",
    setYourPrice: "Set your price",
    canChangeThisAnytime: "You can change this anytime",
    pricePerNight: "Price per night (₹)",
    whereIsYourPlaceLocated: "Where's your place located?",
    addressOnlySharedAfterReservation: "Your address is only shared with guests after they've made a reservation",
    useMyCurrentLocation: "Use my current location",
    selectedLocation: "Selected Location",
    clickOnMapToSelectDifferentLocation: "Click on the map to select a different location:",
    clickOnMapToSelectYourLocation: "Click on the map to select your location:",
    searchForYourLocation: "Search for your location",
    enterAddressOrSearchForPlace: "Enter address or search for a place",
    forNowPleaseUseCurrentLocationOption: "For now, please use the \"Use my current location\" option above",
    back: "Back",
    next: "Next",
    saving: "Saving...",
    // Property types
    house: "House",
    flatApartment: "Flat/apartment",
    barn: "Barn",
    bedAndBreakfast: "Bed & breakfast",
    boat: "Boat",
    cabin: "Cabin",
    campervanMotorhome: "Campervan/motorhome",
    casaParticular: "Casa particular",
    castle: "Castle",
    cave: "Cave",
    container: "Container",
    cycladicHome: "Cycladic home",
    dammuso: "Dammuso",
    dome: "Dome",
    earthHome: "Earth home",
    farm: "Farm",
    guestHouse: "Guest house",
    hotel: "Hotel",
    houseboat: "Houseboat",
    riad: "Riad",
    ryokan: "Ryokan",
    shepherdsHut: "Shepherd's hut",
    tent: "Tent",
    tinyHome: "Tiny home",
    tower: "Tower",
    treeHouse: "Tree house",
    trullo: "Trullo",
    windmill: "Windmill",
    yurt: "Yurt",
  },
  hi: {
    homes: "घर",
    experiences: "अनुभव",
    services: "सेवाएँ",
    support: "सहायता",
    hosting: "होस्टिंग",
    travelBnbBrand: "TravelBnb",
    discover: "खोजें",
    helpCenter: "हेल्प सेंटर",
    airCover: "एयरकवर",
    antiDiscrimination: "भेदभाव विरोध",
    disabilitySupport: "विकलांगता सहायता",
    travelBnbYourHome: "अपने घर को TravelBnb पर सूचीबद्ध करें",
    airCoverForHosts: "होस्ट के लिए एयरकवर",
    hostingResources: "होस्टिंग संसाधन",
    communityForum: "समुदाय फ़ोरम",
    newsroom: "न्यूज़रूम",
    investors: "निवेशक",
    careers: "करियर",
    giftCards: "गिफ्ट कार्ड",
    topRatedStays: "टॉप-रेटेड स्टे",
    privacy: "गोपनीयता",
    terms: "नियम",
    sitemap: "साइटमैप",
    host: "होस्ट",
    detectLocation: "मेरा स्थान पता करें",
    editHostedPlaces: "होस्ट की गई जगहें संपादित करें",
    logout: "लॉग आउट",
    languageAndRegion: "भाषा और क्षेत्र",
    currency: "मुद्रा",
    suggestedLanguagesRegions: "अनुशंसित भाषाएँ और क्षेत्र",
    chooseLanguageRegion: "भाषा और क्षेत्र चुनें",
    done: "पूरा",
    where: "कहाँ",
    searchDestinations: "गंतव्य खोजें",
    checkIn: "चेक-इन",
    checkOut: "चेक-आउट",
    addDates: "तिथियाँ जोड़ें",
    who: "कौन",
    addGuests: "मेहमान जोड़ें",
    adults: "वयस्क",
    children: "बच्चे",
    infants: "शिशु",
    pets: "पालतू",
    ages13Plus: "13 वर्ष या अधिक",
    ages2to12: "2–12 वर्ष",
    under2: "2 वर्ष से कम",
    serviceAnimal: "सेवा पशु ला रहे हैं?",
    datesLabel: "तिथियाँ",
    monthsLabel: "महीने",
    flexibleLabel: "लचीला",
    exactDates: "सटीक तिथियाँ",
    homePopularInCity: "वाराणसी में लोकप्रिय घर",
    popularHomesIn: "लोकप्रिय घर",
    homeRecentlyHosted: "हाल ही में होस्ट किया गया",
    homeAvailableThisWeekend: "इस सप्ताहांत उपलब्ध",
    noImage: "कोई छवि नहीं",
    loading: "लोड हो रहा है…",
    showAllPhotos: "सभी फ़ोटो देखें",
    aboutThisPlace: "इस स्थान के बारे में",
    bathrooms: "बाथरूम",
    guestFavourites: "मेहमानों की पसंद",
    standoutAmenities: "विशेष सुविधाएँ",
    safetyItems: "सुरक्षा वस्तुएँ",
    locationLabel: "स्थान",
    loadingMap: "मानचित्र लोड हो रहा है...",
    coordinates: "निर्देशांक",
    checkInCaps: "चेक-इन",
    checkoutCaps: "चेक-आउट",
    guestsCaps: "मेहमान",
    close: "बंद करें",
    reserve: "बुक करें",
    wontBeChargedYet: "अभी शुल्क नहीं लगेगा",
    // Host page translations
    letsStartWithBasics: "बुनियादी बातों से शुरू करते हैं",
    whichBestDescribesYourPlace: "इनमें से कौन सा आपकी जगह का सबसे अच्छा वर्णन करता है?",
    confirmYourAddress: "अपना पता पुष्टि करें",
    countryRegion: "देश/क्षेत्र",
    flatHouseOptional: "फ्लैट, घर, आदि (वैकल्पिक)",
    streetAddress: "सड़क का पता",
    landmark: "लैंडमार्क",
    locality: "स्थानीय क्षेत्र",
    city: "शहर",
    searchOrSelectStateUT: "राज्य/केंद्र शासित प्रदेश खोजें या चुनें",
    nearbyLandmarkOptional: "पास का लैंडमार्क (वैकल्पिक)",
    districtLocalityOptional: "जिला/क्षेत्र (वैकल्पिक)",
    cityTown: "शहर/कस्बा",
    stateUT: "राज्य/केंद्र शासित प्रदेश",
    pinCode: "पिन कोड",
    howManyPeopleCanStay: "यहाँ कितने लोग रह सकते हैं?",
    guests: "मेहमान",
    bedrooms: "बेडरूम",
    beds: "बेड",
    doesEveryBedroomHaveLock: "क्या हर बेडरूम में ताला है?",
    yes: "हाँ",
    no: "नहीं",
    whatKindOfBathroomsAvailable: "मेहमानों के लिए किस तरह के बाथरूम उपलब्ध हैं?",
    privateAndAttached: "निजी और संलग्न",
    connectedToGuestRoom: "मेहमान के कमरे से जुड़ा और केवल उनके लिए।",
    dedicated: "समर्पित",
    privateButAccessedViaSharedSpace: "निजी, लेकिन एक साझा स्थान जैसे हॉलवे के माध्यम से पहुँचा जाता है।",
    shared: "साझा",
    sharedWithOtherPeople: "अन्य लोगों के साथ साझा।",
    whoElseMightBeThere: "और कौन वहाँ हो सकता है?",
    guestsNeedToKnowEncounterOthers: "मेहमानों को जानना चाहिए कि क्या वे अपने प्रवास के दौरान अन्य लोगों से मिलेंगे।",
    me: "मैं",
    myFamily: "मेरा परिवार",
    otherGuests: "अन्य मेहमान",
    flatmatesHousemates: "फ्लैटमेट/हाउसमेट",
    tellGuestsWhatYourPlaceHasToOffer: "मेहमानों को बताएं कि आपकी जगह में क्या पेशकश है",
    canAddMoreAmenitiesAfterPublish: "आप अपनी लिस्टिंग प्रकाशित करने के बाद और सुविधाएं जोड़ सकते हैं।",
    whatAboutTheseGuestFavourites: "इन मेहमान पसंदीदा के बारे में क्या?",
    wifi: "वाईफाई",
    tv: "टीवी",
    kitchen: "रसोई",
    washingMachine: "वाशिंग मशीन",
    freeParkingOnPremises: "परिसर में मुफ्त पार्किंग",
    paidParkingOnPremises: "परिसर में भुगतान पार्किंग",
    airConditioning: "एयर कंडीशनिंग",
    dedicatedWorkspace: "समर्पित कार्यक्षेत्र",
    doYouHaveAnyStandoutAmenities: "क्या आपके पास कोई विशेष सुविधाएं हैं?",
    pool: "पूल",
    hotTub: "हॉट टब",
    patio: "पेटियो",
    bbqGrill: "बीबीक्यू ग्रिल",
    outdoorDiningArea: "बाहरी भोजन क्षेत्र",
    firepit: "अलाव",
    poolTable: "पूल टेबल",
    indoorFireplace: "इनडोर फायरप्लेस",
    piano: "पियानो",
    exerciseEquipment: "व्यायाम उपकरण",
    lakeAccess: "झील पहुंच",
    beachAccess: "समुद्र तट पहुंच",
    skiInOut: "स्की-इन/आउट",
    outdoorShower: "बाहरी शावर",
    doYouHaveAnyOfTheseSafetyItems: "क्या आपके पास इनमें से कोई सुरक्षा वस्तुएं हैं?",
    smokeAlarm: "धुआं अलार्म",
    firstAidKit: "प्राथमिक चिकित्सा किट",
    fireExtinguisher: "अग्निशामक",
    carbonMonoxideAlarm: "कार्बन मोनोऑक्साइड अलार्म",
    addSomePhotosOfYourPlace: "अपनी जगह की कुछ तस्वीरें जोड़ें",
    need5PhotosToGetStarted: "शुरू करने के लिए आपको 5 तस्वीरों की आवश्यकता होगी। आप बाद में और जोड़ सकते हैं या बदलाव कर सकते हैं।",
    addPhotos: "तस्वीरें जोड़ें",
    remove: "हटाएं",
    setYourPrice: "अपनी कीमत निर्धारित करें",
    canChangeThisAnytime: "आप इसे कभी भी बदल सकते हैं",
    pricePerNight: "प्रति रात कीमत (₹)",
    whereIsYourPlaceLocated: "आपकी जगह कहाँ स्थित है?",
    addressOnlySharedAfterReservation: "आपका पता केवल मेहमानों के साथ तब साझा किया जाता है जब वे आरक्षण कर चुके हों",
    useMyCurrentLocation: "मेरा वर्तमान स्थान उपयोग करें",
    selectedLocation: "चयनित स्थान",
    clickOnMapToSelectDifferentLocation: "अलग स्थान चुनने के लिए मानचित्र पर क्लिक करें:",
    clickOnMapToSelectYourLocation: "अपना स्थान चुनने के लिए मानचित्र पर क्लिक करें:",
    searchForYourLocation: "अपने स्थान की खोज करें",
    enterAddressOrSearchForPlace: "पता दर्ज करें या किसी स्थान की खोज करें",
    forNowPleaseUseCurrentLocationOption: "अभी के लिए, कृपया ऊपर दिए गए \"मेरा वर्तमान स्थान उपयोग करें\" विकल्प का उपयोग करें",
    back: "वापस",
    next: "अगला",
    saving: "सहेजा जा रहा है...",
    // Property types
    house: "घर",
    flatApartment: "फ्लैट/अपार्टमेंट",
    barn: "खलिहान",
    bedAndBreakfast: "बेड एंड ब्रेकफास्ट",
    boat: "नाव",
    cabin: "झोपड़ी",
    campervanMotorhome: "कैम्परवैन/मोटरहोम",
    casaParticular: "कासा पार्टिकुलर",
    castle: "महल",
    cave: "गुफा",
    container: "कंटेनर",
    cycladicHome: "साइक्लेडिक होम",
    dammuso: "डैमुसो",
    dome: "गुंबद",
    earthHome: "अर्थ होम",
    farm: "खेत",
    guestHouse: "गेस्ट हाउस",
    hotel: "होटल",
    houseboat: "हाउसबोट",
    riad: "रियाद",
    ryokan: "रयोकन",
    shepherdsHut: "चरवाहे की झोपड़ी",
    tent: "तंबू",
    tinyHome: "टिनी होम",
    tower: "टावर",
    treeHouse: "ट्री हाउस",
    trullo: "ट्रुलो",
    windmill: "विंडमिल",
    yurt: "यूर्ट",
  },
  kn: {
    homes: "ಮನೆಗಳು",
    experiences: "ಅನುಭವಗಳು",
    services: "ಸೇವೆಗಳು",
    support: "ಸಹಾಯ",
    hosting: "ಹೋಸ್ಟಿಂಗ್",
    travelBnbBrand: "TravelBnb",
    discover: "ಅನ್ವೇಷಿಸಿ",
    helpCenter: "ಸಹಾಯ ಕೇಂದ್ರ",
    airCover: "ಏರ್‌ಕವರ್",
    antiDiscrimination: "ವೈಷಮ್ಯ ವಿರೋಧ",
    disabilitySupport: "ವಿಕಲಚೇತನರಿಗೆ ಬೆಂಬಲ",
    travelBnbYourHome: "ನಿಮ್ಮ ಮನೆಯನ್ನು TravelBnb ನಲ್ಲಿ ಪಟ್ಟಿಮಾಡಿ",
    airCoverForHosts: "ಹೋಸ್ಟ್‌ಗಳಿಗೆ ಏರ್‌ಕವರ್",
    hostingResources: "ಹೋಸ್ಟಿಂಗ್ ಸಂಪನ್ಮೂಲಗಳು",
    communityForum: "ಸಮುದಾಯ ವೇದಿಕೆ",
    newsroom: "ಸುದ್ದಿಗೋಷ್ಠಿ",
    investors: "ಹೂಡಿಕೆದಾರರು",
    careers: "ಕರಿಯರ್‌ಗಳು",
    giftCards: "ಉಡುಗೊರೆ ಕಾರ್ಡ್‌ಗಳು",
    topRatedStays: "ಅತ್ಯುತ್ತಮ ಮೌಲ್ಯಾಂಕಿತ ವಾಸಸ್ತಾನಗಳು",
    privacy: "ಗೌಪ್ಯತೆ",
    terms: "ನಿಯಮಗಳು",
    sitemap: "ಸೈಟ್‌ಮ್ಯಾಪ್",
    host: "ಆತಿಥೇಯ",
    detectLocation: "ನನ್ನ ಸ್ಥಳವನ್ನು ಕಂಡುಹಿಡಿ",
    editHostedPlaces: "ಆತಿಥೇಯ ಸ್ಥಳಗಳನ್ನು ಸಂಪಾದಿಸಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    languageAndRegion: "ಭಾಷೆ ಮತ್ತು ಪ್ರದೇಶ",
    currency: "ಕರೆನ್ಸಿ",
    suggestedLanguagesRegions: "ಶಿಫಾರಸು ಭಾಷೆಗಳು ಮತ್ತು ಪ್ರದೇಶಗಳು",
    chooseLanguageRegion: "ಭಾಷೆ ಮತ್ತು ಪ್ರದೇಶವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    done: "ಆಯಿತು",
    where: "ಎಲ್ಲಿ",
    searchDestinations: "ಗಮ್ಯಸ್ಥಾನಗಳನ್ನು ಹುಡುಕಿ",
    checkIn: "ಚೆಕ್-ಇನ್",
    checkOut: "ಚೆಕ್-ಔಟ್",
    addDates: "ದಿನಾಂಕಗಳನ್ನು ಸೇರಿಸಿ",
    
    addGuests: "ಅತಿಥಿಗಳನ್ನು ಸೇರಿಸಿ",
    adults: "ವಯಸ್ಕರು",
    children: "ಮಕ್ಕಳು",
    infants: "ಶಿಶುಗಳು",
    pets: "ಪಾಲ್ತು ಪ್ರಾಣಿಗಳು",
    ages13Plus: "13 ವರ್ಷ ಅಥವಾ ಹೆಚ್ಚು",
    ages2to12: "2–12 ವರ್ಷ",
    under2: "2 ಕ್ಕಿಂತ ಕಡಿಮೆ",
    serviceAnimal: "ಸೇವಾ ಪ್ರಾಣಿಯನ್ನು ತರ್ತಿದ್ದೀರಾ?",
    datesLabel: "ದಿನಗಳು",
    monthsLabel: "ತಿಂಗಳುಗಳು",
    flexibleLabel: "ಲಚಿಲಿಕೆ",
    exactDates: "ನಿಖರ ದಿನಗಳು",
    homePopularInCity: "ವಾರಾಣಸಿಯಲ್ಲಿ ಜನಪ್ರಿಯ ಮನೆಗಳು",
    popularHomesIn: "ಜನಪ್ರಿಯ ಮನೆಗಳು",
    homeRecentlyHosted: "ಇತ್ತೀಚೆಗೆ ಆತಿಥ್ಯ ನೀಡಲಾಗಿದೆ",
    homeAvailableThisWeekend: "ಈ ವಾರಾಂತ್ಯ ಲಭ್ಯ",
    noImage: "ಚಿತ್ರ ಇಲ್ಲ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
    showAllPhotos: "ಎಲ್ಲಾ ಫೋಟೋಗಳನ್ನು ನೋಡಿ",
    aboutThisPlace: "ಈ ಸ್ಥಳದ ಬಗ್ಗೆ",
    bathrooms: "ಬಾತ್‌ರೂಮ್‌ಗಳು",
    guestFavourites: "ಅತಿಥಿಗಳ ಮೆಚ್ಚಿನವು",
    standoutAmenities: "ಮುಖ್ಯ ಸೌಕರ್ಯಗಳು",
    safetyItems: "ಭದ್ರತಾ ವಸ್ತುಗಳು",
    locationLabel: "ಸ್ಥಳ",
    loadingMap: "ನಕ್ಷೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    coordinates: "ಸ್ಥಾನಾಂಕಗಳು",
    checkInCaps: "ಚೆಕ್-ಇನ್",
    checkoutCaps: "ಚೆಕ್‌ಔಟ್",
    guestsCaps: "ಅತಿಥಿಗಳು",
    close: "ಮುಚ್ಚಿ",
    reserve: "ರಿಸರ್ವ್",
    wontBeChargedYet: "ಈಗ ಶುಲ್ಕ ವಿಧಿಸಲಾಗುವುದಿಲ್ಲ",
    // Host page translations
    letsStartWithBasics: "ಮೂಲಭೂತ ವಿಷಯಗಳೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸೋಣ",
    whichBestDescribesYourPlace: "ಇವುಗಳಲ್ಲಿ ಯಾವುದು ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಉತ್ತಮವಾಗಿ ವಿವರಿಸುತ್ತದೆ?",
    confirmYourAddress: "ನಿಮ್ಮ ವಿಳಾಸವನ್ನು ದೃಢೀಕರಿಸಿ",
    countryRegion: "ದೇಶ/ಪ್ರದೇಶ",
    flatHouseOptional: "ಫ್ಲ್ಯಾಟ್, ಮನೆ, ಇತ್ಯಾದಿ (ಐಚ್ಛಿಕ)",
    streetAddress: "ರಸ್ತೆ ವಿಳಾಸ",
    landmark: "ಲ್ಯಾಂಡ್‌ಮಾರ್ಕ್",
    locality: "ಪರಿಸರ",
    city: "ನಗರ",
    searchOrSelectStateUT: "ರಾಜ್ಯ/ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶ ಹುಡುಕಿ ಅಥವಾ ಆಯ್ಕೆಮಾಡಿ",
    nearbyLandmarkOptional: "ಹತ್ತಿರದ ಮಾರ್ಗಸೂಚಿ (ಐಚ್ಛಿಕ)",
    districtLocalityOptional: "ಜಿಲ್ಲೆ/ಸ್ಥಳ (ಐಚ್ಛಿಕ)",
    cityTown: "ನಗರ/ಪಟ್ಟಣ",
    stateUT: "ರಾಜ್ಯ/ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶ",
    pinCode: "ಪಿನ್ ಕೋಡ್",
    howManyPeopleCanStay: "ಇಲ್ಲಿ ಎಷ್ಟು ಜನರು ಇರಬಹುದು?",
    guests: "ಅತಿಥಿಗಳು",
    bedrooms: "ಮಲಗುವ ಕೊಠಡಿಗಳು",
    beds: "ಮಲಗುವ ಹಾಸಿಗೆಗಳು",
    doesEveryBedroomHaveLock: "ಪ್ರತಿ ಮಲಗುವ ಕೊಠಡಿಗೆ ಬೀಗವಿದೆಯೇ?",
    yes: "ಹೌದು",
    no: "ಇಲ್ಲ",
    whatKindOfBathroomsAvailable: "ಅತಿಥಿಗಳಿಗೆ ಯಾವ ರೀತಿಯ ಸ್ನಾನಗೃಹಗಳು ಲಭ್ಯವಿವೆ?",
    privateAndAttached: "ಖಾಸಗಿ ಮತ್ತು ಲಗತ್ತಿಸಿದೆ",
    connectedToGuestRoom: "ಅತಿಥಿಯ ಕೊಠಡಿಗೆ ಸಂಪರ್ಕಗೊಂಡಿದೆ ಮತ್ತು ಅವರಿಗೆ ಮಾತ್ರ.",
    dedicated: "ಪ್ರತ್ಯೇಕ",
    privateButAccessedViaSharedSpace: "ಖಾಸಗಿ, ಆದರೆ ಹಾಲ್ವೇನಂತಹ ಹಂಚಿಕೆಯ ಸ್ಥಳದ ಮೂಲಕ ಪ್ರವೇಶಿಸಲಾಗುತ್ತದೆ.",
    shared: "ಹಂಚಿಕೊಂಡ",
    sharedWithOtherPeople: "ಇತರ ಜನರೊಂದಿಗೆ ಹಂಚಿಕೊಂಡಿದೆ.",
    whoElseMightBeThere: "ಇನ್ನಾರು ಅಲ್ಲಿ ಇರಬಹುದು?",
    guestsNeedToKnowEncounterOthers: "ಅತಿಥಿಗಳು ತಮ್ಮ ಉಳಿದಿರುವ ಸಮಯದಲ್ಲಿ ಇತರ ಜನರನ್ನು ಎದುರಿಸುತ್ತಾರೆಯೇ ಎಂಬುದನ್ನು ತಿಳಿದುಕೊಳ್ಳಬೇಕು.",
    me: "ನಾನು",
    myFamily: "ನನ್ನ ಕುಟುಂಬ",
    otherGuests: "ಇತರ ಅತಿಥಿಗಳು",
    flatmatesHousemates: "ಫ್ಲ್ಯಾಟ್ ಸಹವಾಸಿಗಳು/ಮನೆ ಸಹವಾಸಿಗಳು",
    tellGuestsWhatYourPlaceHasToOffer: "ಅತಿಥಿಗಳಿಗೆ ನಿಮ್ಮ ಸ್ಥಳದಲ್ಲಿ ಏನು ನೀಡಬಹುದು ಎಂದು ಹೇಳಿ",
    canAddMoreAmenitiesAfterPublish: "ನಿಮ್ಮ ಪಟ್ಟಿಯನ್ನು ಪ್ರಕಟಿಸಿದ ನಂತರ ನೀವು ಹೆಚ್ಚಿನ ಸೌಕರ್ಯಗಳನ್ನು ಸೇರಿಸಬಹುದು.",
    whatAboutTheseGuestFavourites: "ಈ ಅತಿಥಿ ಮೆಚ್ಚಿನಗಳ ಬಗ್ಗೆ ಏನು?",
    wifi: "ವೈಫೈ",
    tv: "ಟಿವಿ",
    kitchen: "ಅಡುಗೆಮನೆ",
    washingMachine: "ಉಡುಗೆ ತೊಳೆಯುವ ಯಂತ್ರ",
    freeParkingOnPremises: "ಆವರಣದಲ್ಲಿ ಉಚಿತ ಪಾರ್ಕಿಂಗ್",
    paidParkingOnPremises: "ಆವರಣದಲ್ಲಿ ಪಾವತಿಸಿದ ಪಾರ್ಕಿಂಗ್",
    airConditioning: "ವಾಯು ಸಂಚಾರ",
    dedicatedWorkspace: "ಪ್ರತ್ಯೇಕ ಕಾರ್ಯ ಸ್ಥಳ",
    doYouHaveAnyStandoutAmenities: "ನಿಮ್ಮಲ್ಲಿ ಯಾವುದಾದರೂ ವಿಶೇಷ ಸೌಕರ್ಯಗಳಿವೆಯೇ?",
    pool: "ಕೊಳ",
    hotTub: "ಬಿಸಿ ಟಬ್",
    patio: "ಪ್ಯಾಟಿಯೋ",
    bbqGrill: "ಬಿಬಿಕ್ಯೂ ಗ್ರಿಲ್",
    outdoorDiningArea: "ಹೊರಾಂಗಣ ಊಟದ ಪ್ರದೇಶ",
    firepit: "ಬೆಂಕಿಯ ಗುಂಡಿ",
    poolTable: "ಪೂಲ್ ಟೇಬಲ್",
    indoorFireplace: "ಒಳಾಂಗಣ ಅಗ್ನಿಕುಂಡ",
    piano: "ಪಿಯಾನೋ",
    exerciseEquipment: "ವ್ಯಾಯಾಮ ಸಲಕರಣೆ",
    lakeAccess: "ಸರೋವರ ಪ್ರವೇಶ",
    beachAccess: "ಕಡಲತೀರ ಪ್ರವೇಶ",
    skiInOut: "ಸ್ಕೀ-ಇನ್/ಔಟ್",
    outdoorShower: "ಹೊರಾಂಗಣ ಶವರ್",
    doYouHaveAnyOfTheseSafetyItems: "ನಿಮ್ಮಲ್ಲಿ ಈ ಭದ್ರತಾ ವಸ್ತುಗಳಲ್ಲಿ ಯಾವುದಾದರೂ ಇದೆಯೇ?",
    smokeAlarm: "ಹೊಗೆ ಎಚ್ಚರಿಕೆ",
    firstAidKit: "ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಕಿಟ್",
    fireExtinguisher: "ಬೆಂಕಿ ನಂದಕ",
    carbonMonoxideAlarm: "ಕಾರ್ಬನ್ ಮೊನಾಕ್ಸೈಡ್ ಎಚ್ಚರಿಕೆ",
    addSomePhotosOfYourPlace: "ನಿಮ್ಮ ಸ್ಥಳದ ಕೆಲವು ಫೋಟೋಗಳನ್ನು ಸೇರಿಸಿ",
    need5PhotosToGetStarted: "ಪ್ರಾರಂಭಿಸಲು ನಿಮಗೆ 5 ಫೋಟೋಗಳು ಬೇಕಾಗುತ್ತವೆ. ನೀವು ನಂತರ ಹೆಚ್ಚು ಸೇರಿಸಬಹುದು ಅಥವಾ ಬದಲಾವಣೆಗಳನ್ನು ಮಾಡಬಹುದು.",
    addPhotos: "ಫೋಟೋಗಳನ್ನು ಸೇರಿಸಿ",
    remove: "ತೆಗೆದುಹಾಕಿ",
    setYourPrice: "ನಿಮ್ಮ ಬೆಲೆಯನ್ನು ನಿಗದಿಪಡಿಸಿ",
    canChangeThisAnytime: "ನೀವು ಇದನ್ನು ಯಾವಾಗಲೂ ಬದಲಾಯಿಸಬಹುದು",
    pricePerNight: "ರಾತ್ರಿಗೆ ಬೆಲೆ (₹)",
    whereIsYourPlaceLocated: "ನಿಮ್ಮ ಸ್ಥಳ ಎಲ್ಲಿದೆ?",
    addressOnlySharedAfterReservation: "ಅತಿಥಿಗಳು ಕಾಯ್ದಿರಿಸಿದ ನಂತರ ಮಾತ್ರ ನಿಮ್ಮ ವಿಳಾಸವನ್ನು ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತದೆ",
    useMyCurrentLocation: "ನನ್ನ ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಬಳಸಿ",
    selectedLocation: "ಆಯ್ಕೆಮಾಡಿದ ಸ್ಥಳ",
    clickOnMapToSelectDifferentLocation: "ವಿಭಿನ್ನ ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಲು ನಕ್ಷೆಯ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ:",
    clickOnMapToSelectYourLocation: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಲು ನಕ್ಷೆಯ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ:",
    searchForYourLocation: "ನಿಮ್ಮ ಸ್ಥಳಕ್ಕಾಗಿ ಹುಡುಕಿ",
    enterAddressOrSearchForPlace: "ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ ಅಥವಾ ಸ್ಥಳಕ್ಕಾಗಿ ಹುಡುಕಿ",
    forNowPleaseUseCurrentLocationOption: "ಈಗಾಗಲೇ, ದಯವಿಟ್ಟು ಮೇಲಿನ \"ನನ್ನ ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಬಳಸಿ\" ಆಯ್ಕೆಯನ್ನು ಬಳಸಿ",
    back: "ಹಿಂದಕ್ಕೆ",
    next: "ಮುಂದೆ",
    saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    // Property types
    house: "ಮನೆ",
    flatApartment: "ಫ್ಲ್ಯಾಟ್/ಅಪಾರ್ಟ್ಮೆಂಟ್",
    barn: "ಕಣಜ",
    bedAndBreakfast: "ಬೆಡ್ ಅಂಡ್ ಬ್ರೆಕ್‌ಫಾಸ್ಟ್",
    boat: "ಪಡವು",
    cabin: "ಕುಟೀರ",
    campervanMotorhome: "ಕ್ಯಾಂಪರ್ವ್ಯಾನ್/ಮೋಟಾರ್‌ಹೋಮ್",
    casaParticular: "ಕಾಸಾ ಪಾರ್ಟಿಕ್ಯುಲರ್",
    castle: "ಕೋಟೆ",
    cave: "ಗುಹೆ",
    container: "ಕಂಟೇನರ್",
    cycladicHome: "ಸೈಕ್ಲಾಡಿಕ್ ಹೋಮ್",
    dammuso: "ಡ್ಯಾಮುಸೋ",
    dome: "ಗುಮ್ಮಟ",
    earthHome: "ಅರ್ಥ್ ಹೋಮ್",
    farm: "ಕೃಷಿ ಭೂಮಿ",
    guestHouse: "ಗೆಸ್ಟ್ ಹೌಸ್",
    hotel: "ಹೋಟೆಲ್",
    houseboat: "ಹೌಸ್‌ಬೋಟ್",
    riad: "ರಿಯಾದ್",
    ryokan: "ರ್ಯೋಕಾನ್",
    shepherdsHut: "ಕುರುಬರ ಕುಟೀರ",
    tent: "ಗುಡಾರ",
    tinyHome: "ಟಿನಿ ಹೋಮ್",
    tower: "ಗೋಪುರ",
    treeHouse: "ಟ್ರೀ ಹೌಸ್",
    trullo: "ಟ್ರುಲ್ಲೋ",
    windmill: "ಗಾಳಿ ಗಿರಣಿ",
    yurt: "ಯುರ್ಟ್",
  },
  mr: {
    homes: "घरे",
    experiences: "अनुभव",
    services: "सेवा",
    support: "मदत",
    hosting: "होस्टिंग",
    travelBnbBrand: "TravelBnb",
    discover: "शोध",
    helpCenter: "मदत केंद्र",
    airCover: "एअरकव्हर",
    antiDiscrimination: "भेदभावविरोध",
    disabilitySupport: "अपंगत्व सहाय्य",
    travelBnbYourHome: "तुमचे घर TravelBnb वर सूचीबद्ध करा",
    airCoverForHosts: "होस्टसाठी एअरकव्हर",
    hostingResources: "होस्टिंग साधने",
    communityForum: "समुदाय फोरम",
    newsroom: "न्यूजरूम",
    investors: "गुंतवणूकदार",
    careers: "करिअर्स",
    giftCards: "गिफ्ट कार्ड्स",
    topRatedStays: "उच्च-रेटेड निवास",
    privacy: "गोपनीयता",
    terms: "अटी",
    sitemap: "साइटमॅप",
    host: "होस्ट",
    detectLocation: "माझे स्थान शोधा",
    editHostedPlaces: "होस्ट केलेल्या ठिकाणी संपादित करा",
    logout: "लॉग आउट",
    languageAndRegion: "भाषा आणि प्रदेश",
    currency: "चलन",
    suggestedLanguagesRegions: "सुचवलेल्या भाषा आणि प्रदेश",
    chooseLanguageRegion: "भाषा आणि प्रदेश निवडा",
    done: "पूर्ण",
    where: "कुठे",
    searchDestinations: "स्थळे शोधा",
    checkIn: "चेक-इन",
    checkOut: "चेक-आऊट",
    addDates: "तारखा जोडा",
    who: "कोण",
    addGuests: "मेहमान जोडा",
    adults: "प्रौढ",
    children: "मुले",
    infants: "बालक",
    pets: "पाळीव प्राणी",
    ages13Plus: "१३ वर्षे किंवा अधिक",
    ages2to12: "२–१२ वर्षे",
    under2: "२ वर्षांखालील",
    serviceAnimal: "सेवा प्राणी आणत आहात?",
    datesLabel: "तारखा",
    monthsLabel: "महिने",
    flexibleLabel: "लवचिक",
    exactDates: "नेमक्या तारखा",
    homePopularInCity: "वाराणसीतील लोकप्रिय घरे",
    popularHomesIn: "लोकप्रिय घरे",
    homeRecentlyHosted: "अलीकडे होस्ट केलेले",
    homeAvailableThisWeekend: "या आठवड्याच्या शेवटी उपलब्ध",
    noImage: "प्रतिमा नाही",
    loading: "लोड होत आहे…",
    showAllPhotos: "सर्व फोटो पहा",
    aboutThisPlace: "या ठिकाणाबद्दल",
    bathrooms: "बाथरूम",
    guestFavourites: "मेहमानांची आवड",
    standoutAmenities: "लक्षणीय सुविधा",
    safetyItems: "सुरक्षा वस्तू",
    locationLabel: "स्थान",
    loadingMap: "नकाशा लोड होत आहे...",
    coordinates: "निर्देशांक",
    checkInCaps: "चेक-इन",
    checkoutCaps: "चेक-आउट",
    guestsCaps: "मेहमान",
    close: "बंद",
    reserve: "राखीव करा",
    wontBeChargedYet: "आता शुल्क आकारले जाणार नाही",
    // Host page translations
    letsStartWithBasics: "मूलभूत गोष्टींपासून सुरुवात करूया",
    whichBestDescribesYourPlace: "यापैकी कोणते तुमच्या जागेचे सर्वोत्तम वर्णन करते?",
    confirmYourAddress: "तुमचा पत्ता पुष्टी करा",
    countryRegion: "देश/प्रदेश",
    flatHouseOptional: "फ्लॅट, घर, इ. (पर्यायी)",
    streetAddress: "रस्त्याचा पत्ता",
    landmark: "ओळखचिन्ह",
    locality: "स्थानिक",
    city: "शहर",
    searchOrSelectStateUT: "राज्य/केंद्रशासित प्रदेश शोधा किंवा निवडा",
    nearbyLandmarkOptional: "जवळचे ओळखचिन्ह (पर्यायी)",
    districtLocalityOptional: "जिल्हा/स्थानिक (पर्यायी)",
    cityTown: "शहर/कसबा",
    stateUT: "राज्य/केंद्रशासित प्रदेश",
    pinCode: "पिन कोड",
    howManyPeopleCanStay: "येथे किती लोक राहू शकतात?",
    guests: "पाहुणे",
    bedrooms: "शयनकक्षे",
    beds: "पलंग",
    doesEveryBedroomHaveLock: "प्रत्येक शयनकक्षात कुलूप आहे का?",
    yes: "होय",
    no: "नाही",
    whatKindOfBathroomsAvailable: "पाहुण्यांसाठी कोणत्या प्रकारचे स्नानगृहे उपलब्ध आहेत?",
    privateAndAttached: "खाजगी आणि जोडलेले",
    connectedToGuestRoom: "पाहुण्याच्या खोलीशी जोडलेले आणि फक्त त्यांच्यासाठी.",
    dedicated: "समर्पित",
    privateButAccessedViaSharedSpace: "खाजगी, पण हॉलवेसारख्या सामायिक जागेद्वारे प्रवेश.",
    shared: "सामायिक",
    sharedWithOtherPeople: "इतर लोकांसोबत सामायिक.",
    whoElseMightBeThere: "आणखी कोण तेथे असू शकते?",
    guestsNeedToKnowEncounterOthers: "पाहुण्यांना माहित असावे की त्यांच्या राहण्यादरम्यान ते इतर लोकांना भेटतील का.",
    me: "मी",
    myFamily: "माझे कुटुंब",
    otherGuests: "इतर पाहुणे",
    flatmatesHousemates: "फ्लॅटमेट्स/हाऊसमेट्स",
    tellGuestsWhatYourPlaceHasToOffer: "पाहुण्यांना सांगा की तुमच्या जागेत काय ऑफर आहे",
    canAddMoreAmenitiesAfterPublish: "तुम्ही तुमची लिस्टिंग प्रकाशित केल्यानंतर आणखी सुविधा जोडू शकता.",
    whatAboutTheseGuestFavourites: "या पाहुणे आवडींबद्दल काय?",
    wifi: "वायफाय",
    tv: "टीव्ही",
    kitchen: "स्वयंपाकघर",
    washingMachine: "वॉशिंग मशीन",
    freeParkingOnPremises: "परिसरात मोफत पार्किंग",
    paidParkingOnPremises: "परिसरात पेड पार्किंग",
    airConditioning: "वातानुकूलन",
    dedicatedWorkspace: "समर्पित कार्यक्षेत्र",
    doYouHaveAnyStandoutAmenities: "तुमच्याकडे काही उत्कृष्ट सुविधा आहेत का?",
    pool: "पूल",
    hotTub: "हॉट टब",
    patio: "पॅटिओ",
    bbqGrill: "बीबीक्यू ग्रिल",
    outdoorDiningArea: "बाहेरील जेवणाचे क्षेत्र",
    firepit: "अग्निकुंड",
    poolTable: "पूल टेबल",
    indoorFireplace: "घरातील अग्निकुंड",
    piano: "पियानो",
    exerciseEquipment: "व्यायाम उपकरणे",
    lakeAccess: "तळे प्रवेश",
    beachAccess: "समुद्रकिनारा प्रवेश",
    skiInOut: "स्की-इन/आउट",
    outdoorShower: "बाहेरील शॉवर",
    doYouHaveAnyOfTheseSafetyItems: "तुमच्याकडे यापैकी काही सुरक्षा वस्तू आहेत का?",
    smokeAlarm: "धूर अलार्म",
    firstAidKit: "प्राथमिक उपचार किट",
    fireExtinguisher: "अग्निशामक",
    carbonMonoxideAlarm: "कार्बन मोनोऑक्साइड अलार्म",
    addSomePhotosOfYourPlace: "तुमच्या जागेचे काही फोटो जोडा",
    need5PhotosToGetStarted: "सुरुवात करण्यासाठी तुम्हाला 5 फोटो लागतील. तुम्ही नंतर आणखी जोडू शकता किंवा बदल करू शकता.",
    addPhotos: "फोटो जोडा",
    remove: "काढा",
    setYourPrice: "तुमची किंमत सेट करा",
    canChangeThisAnytime: "तुम्ही हे कधीही बदलू शकता",
    pricePerNight: "प्रति रात्री किंमत (₹)",
    whereIsYourPlaceLocated: "तुमची जागा कुठे आहे?",
    addressOnlySharedAfterReservation: "पाहुण्यांनी आरक्षण केल्यानंतरच तुमचा पत्ता सामायिक केला जातो",
    useMyCurrentLocation: "माझे सध्याचे स्थान वापरा",
    selectedLocation: "निवडलेले स्थान",
    clickOnMapToSelectDifferentLocation: "वेगळे स्थान निवडण्यासाठी नकाशावर क्लिक करा:",
    clickOnMapToSelectYourLocation: "तुमचे स्थान निवडण्यासाठी नकाशावर क्लिक करा:",
    searchForYourLocation: "तुमच्या स्थानासाठी शोधा",
    enterAddressOrSearchForPlace: "पत्ता प्रविष्ट करा किंवा ठिकाण शोधा",
    forNowPleaseUseCurrentLocationOption: "आत्तासाठी, कृपया वरील \"माझे सध्याचे स्थान वापरा\" पर्याय वापरा",
    back: "मागे",
    next: "पुढे",
    saving: "सेव्ह होत आहे...",
    // Property types
    house: "घर",
    flatApartment: "फ्लॅट/अपार्टमेंट",
    barn: "कोठार",
    bedAndBreakfast: "बेड अँड ब्रेकफास्ट",
    boat: "बोट",
    cabin: "कुटीर",
    campervanMotorhome: "कॅम्परव्हॅन/मोटरहोम",
    casaParticular: "कासा पार्टिकुलर",
    castle: "किल्ला",
    cave: "गुहा",
    container: "कंटेनर",
    cycladicHome: "सायक्लॅडिक होम",
    dammuso: "डॅमुसो",
    dome: "गुंबद",
    earthHome: "अर्थ होम",
    farm: "शेत",
    guestHouse: "गेस्ट हाऊस",
    hotel: "हॉटेल",
    houseboat: "हाऊसबोट",
    riad: "रियाद",
    ryokan: "र्योकान",
    shepherdsHut: "गड्याचे कुटीर",
    tent: "तंबू",
    tinyHome: "टिनी होम",
    tower: "टॉवर",
    treeHouse: "ट्री हाऊस",
    trullo: "ट्रुलो",
    windmill: "विंडमिल",
    yurt: "युर्ट",
  },
  ar: {
    homes: "المنازل",
    experiences: "التجارب",
    services: "الخدمات",
    support: "الدعم",
    hosting: "الاستضافة",
    travelBnbBrand: "TravelBnb",
    discover: "اكتشف",
    helpCenter: "مركز المساعدة",
    airCover: "تغطية الهواء",
    antiDiscrimination: "مكافحة التمييز",
    disabilitySupport: "دعم ذوي الإعاقة",
    travelBnbYourHome: "اعرض منزلك على TravelBnb",
    airCoverForHosts: "تغطية الهواء للمضيفين",
    hostingResources: "موارد الاستضافة",
    communityForum: "منتدى المجتمع",
    newsroom: "غرفة الأخبار",
    investors: "المستثمرون",
    careers: "الوظائف",
    giftCards: "بطاقات الهدايا",
    topRatedStays: "أعلى الإقامات تقييماً",
    privacy: "الخصوصية",
    terms: "الشروط",
    sitemap: "خريطة الموقع",
    host: "المضيف",
    detectLocation: "اكتشف موقعي",
    editHostedPlaces: "تحرير الأماكن المستضافة",
    logout: "تسجيل الخروج",
    languageAndRegion: "اللغة والمنطقة",
    currency: "العملة",
    suggestedLanguagesRegions: "اللغات والمناطق المقترحة",
    chooseLanguageRegion: "اختر اللغة والمنطقة",
    done: "تم",
    where: "أين",
    searchDestinations: "البحث عن الوجهات",
    checkIn: "تسجيل الوصول",
    checkOut: "تسجيل المغادرة",
    addDates: "إضافة التواريخ",
    who: "من",
    addGuests: "إضافة الضيوف",
    adults: "البالغون",
    children: "الأطفال",
    infants: "الرضع",
    pets: "الحيوانات الأليفة",
    ages13Plus: "13 سنة أو أكثر",
    ages2to12: "2–12 سنة",
    under2: "أقل من سنتين",
    serviceAnimal: "هل تحضر حيوان خدمة؟",
    datesLabel: "التواريخ",
    monthsLabel: "الأشهر",
    flexibleLabel: "مرن",
    exactDates: "التواريخ المحددة",
    homePopularInCity: "المنازل الشائعة في فاراناسي",
    popularHomesIn: "المنازل الشائعة في",
    homeRecentlyHosted: "تم استضافتها مؤخراً",
    homeAvailableThisWeekend: "متاح نهاية هذا الأسبوع",
    noImage: "لا توجد صورة",
    loading: "جاري التحميل…",
    showAllPhotos: "عرض جميع الصور",
    aboutThisPlace: "حول هذا المكان",
    bathrooms: "دورات المياه",
    guestFavourites: "مفضلات الضيوف",
    standoutAmenities: "المرافق المميزة",
    safetyItems: "أدوات السلامة",
    locationLabel: "الموقع",
    loadingMap: "جاري تحميل الخريطة...",
    coordinates: "الإحداثيات",
    checkInCaps: "تسجيل الوصول",
    checkoutCaps: "تسجيل المغادرة",
    guestsCaps: "الضيوف",
    close: "إغلاق",
    reserve: "حجز",
    wontBeChargedYet: "لن يتم تحصيل رسوم الآن",
    // Host page translations
    letsStartWithBasics: "لنبدأ بالأساسيات",
    whichBestDescribesYourPlace: "أي من هذه يصف مكانك بشكل أفضل؟",
    confirmYourAddress: "أكد عنوانك",
    countryRegion: "البلد/المنطقة",
    flatHouseOptional: "شقة، منزل، إلخ (اختياري)",
    streetAddress: "عنوان الشارع",
    landmark: "معلم",
    locality: "المحلية",
    city: "المدينة",
    searchOrSelectStateUT: "ابحث أو اختر الولاية/الإقليم الاتحادي",
    nearbyLandmarkOptional: "معلم قريب (اختياري)",
    districtLocalityOptional: "المنطقة/المحلية (اختياري)",
    cityTown: "المدينة/البلدة",
    stateUT: "الولاية/الإقليم الاتحادي",
    pinCode: "الرمز البريدي",
    howManyPeopleCanStay: "كم عدد الأشخاص الذين يمكنهم الإقامة هنا؟",
    guests: "الضيوف",
    bedrooms: "غرف النوم",
    beds: "الأسرّة",
    doesEveryBedroomHaveLock: "هل كل غرفة نوم لها قفل؟",
    yes: "نعم",
    no: "لا",
    whatKindOfBathroomsAvailable: "ما نوع دورات المياه المتاحة للضيوف؟",
    privateAndAttached: "خاص ومرفق",
    connectedToGuestRoom: "متصل بغرفة الضيف ومخصص لهم فقط.",
    dedicated: "مخصص",
    privateButAccessedViaSharedSpace: "خاص، لكن يُصل إليه عبر مساحة مشتركة مثل الممر.",
    shared: "مشترك",
    sharedWithOtherPeople: "مشترك مع أشخاص آخرين.",
    whoElseMightBeThere: "من آخر قد يكون هناك؟",
    guestsNeedToKnowEncounterOthers: "يحتاج الضيوف لمعرفة ما إذا كانوا سيواجهون أشخاصاً آخرين أثناء إقامتهم.",
    me: "أنا",
    myFamily: "عائلتي",
    otherGuests: "ضيوف آخرون",
    flatmatesHousemates: "زملاء الشقة/المنزل",
    tellGuestsWhatYourPlaceHasToOffer: "أخبر الضيوف بما يقدمه مكانك",
    canAddMoreAmenitiesAfterPublish: "يمكنك إضافة المزيد من المرافق بعد نشر قائمتك.",
    whatAboutTheseGuestFavourites: "ماذا عن مفضلات الضيوف هذه؟",
    wifi: "واي فاي",
    tv: "تلفزيون",
    kitchen: "مطبخ",
    washingMachine: "غسالة ملابس",
    freeParkingOnPremises: "موقف سيارات مجاني في الموقع",
    paidParkingOnPremises: "موقف سيارات مدفوع في الموقع",
    airConditioning: "تكييف هواء",
    dedicatedWorkspace: "مساحة عمل مخصصة",
    doYouHaveAnyStandoutAmenities: "هل لديك أي مرافق مميزة؟",
    pool: "مسبح",
    hotTub: "جاكوزي",
    patio: "فناء",
    bbqGrill: "شواية باربيكيو",
    outdoorDiningArea: "منطقة طعام خارجية",
    firepit: "موقد نار",
    poolTable: "طاولة بلياردو",
    indoorFireplace: "موقد نار داخلي",
    piano: "بيانو",
    exerciseEquipment: "معدات رياضية",
    lakeAccess: "وصول للبحيرة",
    beachAccess: "وصول للشاطئ",
    skiInOut: "تزلج مباشر",
    outdoorShower: "دش خارجي",
    doYouHaveAnyOfTheseSafetyItems: "هل لديك أي من أدوات السلامة هذه؟",
    smokeAlarm: "إنذار الدخان",
    firstAidKit: "صندوق إسعافات أولية",
    fireExtinguisher: "مطفأة حريق",
    carbonMonoxideAlarm: "إنذار أول أكسيد الكربون",
    addSomePhotosOfYourPlace: "أضف بعض الصور لمكانك",
    need5PhotosToGetStarted: "ستحتاج إلى 5 صور للبدء. يمكنك إضافة المزيد أو إجراء تغييرات لاحقاً.",
    addPhotos: "إضافة صور",
    remove: "إزالة",
    setYourPrice: "حدد سعرك",
    canChangeThisAnytime: "يمكنك تغيير هذا في أي وقت",
    pricePerNight: "السعر لكل ليلة (₹)",
    whereIsYourPlaceLocated: "أين يقع مكانك؟",
    addressOnlySharedAfterReservation: "يتم مشاركة عنوانك مع الضيوف فقط بعد قيامهم بالحجز",
    useMyCurrentLocation: "استخدم موقعي الحالي",
    selectedLocation: "الموقع المحدد",
    clickOnMapToSelectDifferentLocation: "انقر على الخريطة لتحديد موقع مختلف:",
    clickOnMapToSelectYourLocation: "انقر على الخريطة لتحديد موقعك:",
    searchForYourLocation: "ابحث عن موقعك",
    enterAddressOrSearchForPlace: "أدخل العنوان أو ابحث عن مكان",
    forNowPleaseUseCurrentLocationOption: "في الوقت الحالي، يرجى استخدام خيار \"استخدم موقعي الحالي\" أعلاه",
    back: "رجوع",
    next: "التالي",
    saving: "جاري الحفظ...",
    // Property types
    house: "منزل",
    flatApartment: "شقة/أباريتمنت",
    barn: "مخزن الحبوب",
    bedAndBreakfast: "سرير وفطور",
    boat: "قارب",
    cabin: "كابينة",
    campervanMotorhome: "عربة سكن/منزل متنقل",
    casaParticular: "كاسا بارتيكولار",
    castle: "قلعة",
    cave: "كهف",
    container: "حاوية",
    cycladicHome: "منزل سيكلادي",
    dammuso: "داموسو",
    dome: "قبة",
    earthHome: "منزل أرضي",
    farm: "مزرعة",
    guestHouse: "بيت ضيافة",
    hotel: "فندق",
    houseboat: "منزل عائم",
    riad: "رياض",
    ryokan: "ريوكان",
    shepherdsHut: "كوخ الراعي",
    tent: "خيمة",
    tinyHome: "منزل صغير",
    tower: "برج",
    treeHouse: "بيت الشجرة",
    trullo: "ترولو",
    windmill: "طاحونة هواء",
    yurt: "يورت",
  },
};

type LanguageContextValue = {
  locale: Locale;
  t: (key: string) => string;
  setLocale: (locale: Locale) => void;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");

  // Load saved locale
  useEffect(() => {
    try {
      const saved = localStorage.getItem("locale") as Locale | null;
      if (saved && ["en", "hi", "kn", "mr", "ar"].includes(saved)) {
        setLocaleState(saved);
      }
    } catch {}
  }, []);

  const setLocale = useCallback((l: Locale) => {
    setLocaleState(l);
    try {
      localStorage.setItem("locale", l);
    } catch {}
  }, []);

  const t = useCallback(
    (key: string) => {
      const dict = dictionaries[locale] || dictionaries.en;
      return dict[key] ?? key;
    },
    [locale]
  );

  const value = useMemo(() => ({ locale, t, setLocale }), [locale, t, setLocale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}


