"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

type Locale = "en" | "hi" | "kn" | "mr";

type Dictionary = Record<string, string>;

const dictionaries: Record<Locale, Dictionary> = {
  en: {
    homes: "Homes",
    experiences: "Experiences",
    services: "Services",
    support: "Support",
    hosting: "Hosting",
    travelBnbBrand: "TravelBnb",
    discover: "Discover",
    helpCenter: "Help Center",
    airCover: "AirCover",
    antiDiscrimination: "Anti-discrimination",
    disabilitySupport: "Disability support",
    travelBnbYourHome: "TravelBnb your home",
    airCoverForHosts: "AirCover for Hosts",
    hostingResources: "Hosting resources",
    communityForum: "Community forum",
    newsroom: "Newsroom",
    investors: "Investors",
    careers: "Careers",
    giftCards: "Gift cards",
    topRatedStays: "Top-rated stays",
    privacy: "Privacy",
    terms: "Terms",
    sitemap: "Sitemap",
    host: "Host",
    detectLocation: "Detect my location",
    editHostedPlaces: "Edit hosted places",
    logout: "Log out",
    languageAndRegion: "Language and region",
    currency: "Currency",
    suggestedLanguagesRegions: "Suggested languages and regions",
    chooseLanguageRegion: "Choose a language and region",
    done: "Done",
    where: "Where",
    searchDestinations: "Search destinations",
    checkIn: "Check in",
    checkOut: "Check out",
    addDates: "Add dates",
    who: "Who",
    addGuests: "Add guests",
    adults: "Adults",
    children: "Children",
    infants: "Infants",
    pets: "Pets",
    ages13Plus: "Ages 13 or above",
    ages2to12: "Ages 2–12",
    under2: "Under 2",
    serviceAnimal: "Bringing a service animal?",
    datesLabel: "Dates",
    monthsLabel: "Months",
    flexibleLabel: "Flexible",
    exactDates: "Exact dates",
    homePopularInCity: "Popular homes in Varanasi",
    homeRecentlyHosted: "Recently hosted",
    homeAvailableThisWeekend: "Available this weekend",
    noImage: "No image",
    loading: "Loading…",
    showAllPhotos: "Show all photos",
    aboutThisPlace: "About this place",
    bathrooms: "Bathrooms",
    privateAttached: "Private and attached",
    dedicated: "Dedicated",
    shared: "Shared",
    guestFavourites: "Guest favourites",
    standoutAmenities: "Standout amenities",
    safetyItems: "Safety items",
    locationLabel: "Location",
    loadingMap: "Loading map...",
    coordinates: "Coordinates",
    checkInCaps: "CHECK-IN",
    checkoutCaps: "CHECKOUT",
    guestsCaps: "GUESTS",
    close: "Close",
    reserve: "Reserve",
    wontBeChargedYet: "You won't be charged yet",
  },
  hi: {
    homes: "घर",
    experiences: "अनुभव",
    services: "सेवाएँ",
    support: "सहायता",
    hosting: "होस्टिंग",
    travelBnbBrand: "TravelBnb",
    discover: "खोजें",
    helpCenter: "हेल्प सेंटर",
    airCover: "एयरकवर",
    antiDiscrimination: "भेदभाव विरोध",
    disabilitySupport: "विकलांगता सहायता",
    travelBnbYourHome: "अपने घर को TravelBnb पर सूचीबद्ध करें",
    airCoverForHosts: "होस्ट के लिए एयरकवर",
    hostingResources: "होस्टिंग संसाधन",
    communityForum: "समुदाय फ़ोरम",
    newsroom: "न्यूज़रूम",
    investors: "निवेशक",
    careers: "करियर",
    giftCards: "गिफ्ट कार्ड",
    topRatedStays: "टॉप-रेटेड स्टे",
    privacy: "गोपनीयता",
    terms: "नियम",
    sitemap: "साइटमैप",
    host: "होस्ट",
    detectLocation: "मेरा स्थान पता करें",
    editHostedPlaces: "होस्ट की गई जगहें संपादित करें",
    logout: "लॉग आउट",
    languageAndRegion: "भाषा और क्षेत्र",
    currency: "मुद्रा",
    suggestedLanguagesRegions: "अनुशंसित भाषाएँ और क्षेत्र",
    chooseLanguageRegion: "भाषा और क्षेत्र चुनें",
    done: "पूरा",
    where: "कहाँ",
    searchDestinations: "गंतव्य खोजें",
    checkIn: "चेक-इन",
    checkOut: "चेक-आउट",
    addDates: "तिथियाँ जोड़ें",
    who: "कौन",
    addGuests: "मेहमान जोड़ें",
    adults: "वयस्क",
    children: "बच्चे",
    infants: "शिशु",
    pets: "पालतू",
    ages13Plus: "13 वर्ष या अधिक",
    ages2to12: "2–12 वर्ष",
    under2: "2 वर्ष से कम",
    serviceAnimal: "सेवा पशु ला रहे हैं?",
    datesLabel: "तिथियाँ",
    monthsLabel: "महीने",
    flexibleLabel: "लचीला",
    exactDates: "सटीक तिथियाँ",
    homePopularInCity: "वाराणसी में लोकप्रिय घर",
    homeRecentlyHosted: "हाल ही में होस्ट किया गया",
    homeAvailableThisWeekend: "इस सप्ताहांत उपलब्ध",
    noImage: "कोई छवि नहीं",
    loading: "लोड हो रहा है…",
    showAllPhotos: "सभी फ़ोटो देखें",
    aboutThisPlace: "इस स्थान के बारे में",
    bathrooms: "बाथरूम",
    privateAttached: "निजी और संलग्न",
    dedicated: "समर्पित",
    shared: "साझा",
    guestFavourites: "मेहमानों की पसंद",
    standoutAmenities: "विशेष सुविधाएँ",
    safetyItems: "सुरक्षा वस्तुएँ",
    locationLabel: "स्थान",
    loadingMap: "मानचित्र लोड हो रहा है...",
    coordinates: "निर्देशांक",
    checkInCaps: "चेक-इन",
    checkoutCaps: "चेक-आउट",
    guestsCaps: "मेहमान",
    close: "बंद करें",
    reserve: "बुक करें",
    wontBeChargedYet: "अभी शुल्क नहीं लगेगा",
  },
  kn: {
    homes: "ಮನೆಗಳು",
    experiences: "ಅನುಭವಗಳು",
    services: "ಸೇವೆಗಳು",
    support: "ಸಹಾಯ",
    hosting: "ಹೋಸ್ಟಿಂಗ್",
    travelBnbBrand: "TravelBnb",
    discover: "ಅನ್ವೇಷಿಸಿ",
    helpCenter: "ಸಹಾಯ ಕೇಂದ್ರ",
    airCover: "ಏರ್‌ಕವರ್",
    antiDiscrimination: "ವೈಷಮ್ಯ ವಿರೋಧ",
    disabilitySupport: "ವಿಕಲಚೇತನರಿಗೆ ಬೆಂಬಲ",
    travelBnbYourHome: "ನಿಮ್ಮ ಮನೆಯನ್ನು TravelBnb ನಲ್ಲಿ ಪಟ್ಟಿಮಾಡಿ",
    airCoverForHosts: "ಹೋಸ್ಟ್‌ಗಳಿಗೆ ಏರ್‌ಕವರ್",
    hostingResources: "ಹೋಸ್ಟಿಂಗ್ ಸಂಪನ್ಮೂಲಗಳು",
    communityForum: "ಸಮುದಾಯ ವೇದಿಕೆ",
    newsroom: "ಸುದ್ದಿಗೋಷ್ಠಿ",
    investors: "ಹೂಡಿಕೆದಾರರು",
    careers: "ಕರಿಯರ್‌ಗಳು",
    giftCards: "ಉಡುಗೊರೆ ಕಾರ್ಡ್‌ಗಳು",
    topRatedStays: "ಅತ್ಯುತ್ತಮ ಮೌಲ್ಯಾಂಕಿತ ವಾಸಸ್ತಾನಗಳು",
    privacy: "ಗೌಪ್ಯತೆ",
    terms: "ನಿಯಮಗಳು",
    sitemap: "ಸೈಟ್‌ಮ್ಯಾಪ್",
    host: "ಆತಿಥೇಯ",
    detectLocation: "ನನ್ನ ಸ್ಥಳವನ್ನು ಕಂಡುಹಿಡಿ",
    editHostedPlaces: "ಆತಿಥೇಯ ಸ್ಥಳಗಳನ್ನು ಸಂಪಾದಿಸಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    languageAndRegion: "ಭಾಷೆ ಮತ್ತು ಪ್ರದೇಶ",
    currency: "ಕರೆನ್ಸಿ",
    suggestedLanguagesRegions: "ಶಿಫಾರಸು ಭಾಷೆಗಳು ಮತ್ತು ಪ್ರದೇಶಗಳು",
    chooseLanguageRegion: "ಭಾಷೆ ಮತ್ತು ಪ್ರದೇಶವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    done: "ಆಯಿತು",
    where: "ಎಲ್ಲಿ",
    searchDestinations: "ಗಮ್ಯಸ್ಥಾನಗಳನ್ನು ಹುಡುಕಿ",
    checkIn: "ಚೆಕ್-ಇನ್",
    checkOut: "ಚೆಕ್-ಔಟ್",
    addDates: "ದಿನಾಂಕಗಳನ್ನು ಸೇರಿಸಿ",
    
    addGuests: "ಅತಿಥಿಗಳನ್ನು ಸೇರಿಸಿ",
    adults: "ವಯಸ್ಕರು",
    children: "ಮಕ್ಕಳು",
    infants: "ಶಿಶುಗಳು",
    pets: "ಪಾಲ್ತು ಪ್ರಾಣಿಗಳು",
    ages13Plus: "13 ವರ್ಷ ಅಥವಾ ಹೆಚ್ಚು",
    ages2to12: "2–12 ವರ್ಷ",
    under2: "2 ಕ್ಕಿಂತ ಕಡಿಮೆ",
    serviceAnimal: "ಸೇವಾ ಪ್ರಾಣಿಯನ್ನು ತರ್ತಿದ್ದೀರಾ?",
    datesLabel: "ದಿನಗಳು",
    monthsLabel: "ತಿಂಗಳುಗಳು",
    flexibleLabel: "ಲಚಿಲಿಕೆ",
    exactDates: "ನಿಖರ ದಿನಗಳು",
    homePopularInCity: "ವಾರಾಣಸಿಯಲ್ಲಿ ಜನಪ್ರಿಯ ಮನೆಗಳು",
    homeRecentlyHosted: "ಇತ್ತೀಚೆಗೆ ಆತಿಥ್ಯ ನೀಡಲಾಗಿದೆ",
    homeAvailableThisWeekend: "ಈ ವಾರಾಂತ್ಯ ಲಭ್ಯ",
    noImage: "ಚಿತ್ರ ಇಲ್ಲ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
    showAllPhotos: "ಎಲ್ಲಾ ಫೋಟೋಗಳನ್ನು ನೋಡಿ",
    aboutThisPlace: "ಈ ಸ್ಥಳದ ಬಗ್ಗೆ",
    bathrooms: "ಬಾತ್‌ರೂಮ್‌ಗಳು",
    privateAttached: "ಖಾಸಗಿ ಮತ್ತು ಲಗತ್ತಿಸಿದೆ",
    dedicated: "ಪ್ರತ್ಯೇಕ",
    shared: "ಹಂಚಿಕೊಂಡ",
    guestFavourites: "ಅತಿಥಿಗಳ ಮೆಚ್ಚಿನವು",
    standoutAmenities: "ಮುಖ್ಯ ಸೌಕರ್ಯಗಳು",
    safetyItems: "ಭದ್ರತಾ ವಸ್ತುಗಳು",
    locationLabel: "ಸ್ಥಳ",
    loadingMap: "ನಕ್ಷೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    coordinates: "ಸ್ಥಾನಾಂಕಗಳು",
    checkInCaps: "ಚೆಕ್-ಇನ್",
    checkoutCaps: "ಚೆಕ್‌ಔಟ್",
    guestsCaps: "ಅತಿಥಿಗಳು",
    close: "ಮುಚ್ಚಿ",
    reserve: "ರಿಸರ್ವ್",
    wontBeChargedYet: "ಈಗ ಶುಲ್ಕ ವಿಧಿಸಲಾಗುವುದಿಲ್ಲ",
  },
  mr: {
    homes: "घरे",
    experiences: "अनुभव",
    services: "सेवा",
    support: "मदत",
    hosting: "होस्टिंग",
    travelBnbBrand: "TravelBnb",
    discover: "शोध",
    helpCenter: "मदत केंद्र",
    airCover: "एअरकव्हर",
    antiDiscrimination: "भेदभावविरोध",
    disabilitySupport: "अपंगत्व सहाय्य",
    travelBnbYourHome: "तुमचे घर TravelBnb वर सूचीबद्ध करा",
    airCoverForHosts: "होस्टसाठी एअरकव्हर",
    hostingResources: "होस्टिंग साधने",
    communityForum: "समुदाय फोरम",
    newsroom: "न्यूजरूम",
    investors: "गुंतवणूकदार",
    careers: "करिअर्स",
    giftCards: "गिफ्ट कार्ड्स",
    topRatedStays: "उच्च-रेटेड निवास",
    privacy: "गोपनीयता",
    terms: "अटी",
    sitemap: "साइटमॅप",
    host: "होस्ट",
    detectLocation: "माझे स्थान शोधा",
    editHostedPlaces: "होस्ट केलेल्या ठिकाणी संपादित करा",
    logout: "लॉग आउट",
    languageAndRegion: "भाषा आणि प्रदेश",
    currency: "चलन",
    suggestedLanguagesRegions: "सुचवलेल्या भाषा आणि प्रदेश",
    chooseLanguageRegion: "भाषा आणि प्रदेश निवडा",
    done: "पूर्ण",
    where: "कुठे",
    searchDestinations: "स्थळे शोधा",
    checkIn: "चेक-इन",
    checkOut: "चेक-आऊट",
    addDates: "तारखा जोडा",
    who: "कोण",
    addGuests: "मेहमान जोडा",
    adults: "प्रौढ",
    children: "मुले",
    infants: "बालक",
    pets: "पाळीव प्राणी",
    ages13Plus: "१३ वर्षे किंवा अधिक",
    ages2to12: "२–१२ वर्षे",
    under2: "२ वर्षांखालील",
    serviceAnimal: "सेवा प्राणी आणत आहात?",
    datesLabel: "तारखा",
    monthsLabel: "महिने",
    flexibleLabel: "लवचिक",
    exactDates: "नेमक्या तारखा",
    homePopularInCity: "वाराणसीतील लोकप्रिय घरे",
    homeRecentlyHosted: "अलीकडे होस्ट केलेले",
    homeAvailableThisWeekend: "या आठवड्याच्या शेवटी उपलब्ध",
    noImage: "प्रतिमा नाही",
    loading: "लोड होत आहे…",
    showAllPhotos: "सर्व फोटो पहा",
    aboutThisPlace: "या ठिकाणाबद्दल",
    bathrooms: "बाथरूम",
    privateAttached: "खाजगी आणि संलग्न",
    dedicated: "समर्पित",
    shared: "सामायिक",
    guestFavourites: "मेहमानांची आवड",
    standoutAmenities: "लक्षणीय सुविधा",
    safetyItems: "सुरक्षा वस्तू",
    locationLabel: "स्थान",
    loadingMap: "नकाशा लोड होत आहे...",
    coordinates: "निर्देशांक",
    checkInCaps: "चेक-इन",
    checkoutCaps: "चेक-आउट",
    guestsCaps: "मेहमान",
    close: "बंद",
    reserve: "राखीव करा",
    wontBeChargedYet: "आता शुल्क आकारले जाणार नाही",
  },
};

type LanguageContextValue = {
  locale: Locale;
  t: (key: string) => string;
  setLocale: (locale: Locale) => void;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");

  // Load saved locale
  useEffect(() => {
    try {
      const saved = localStorage.getItem("locale") as Locale | null;
      if (saved && ["en", "hi", "kn", "mr"].includes(saved)) {
        setLocaleState(saved);
      }
    } catch {}
  }, []);

  const setLocale = useCallback((l: Locale) => {
    setLocaleState(l);
    try {
      localStorage.setItem("locale", l);
    } catch {}
  }, []);

  const t = useCallback(
    (key: string) => {
      const dict = dictionaries[locale] || dictionaries.en;
      return dict[key] ?? key;
    },
    [locale]
  );

  const value = useMemo(() => ({ locale, t, setLocale }), [locale, t, setLocale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}


